trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: imageName
    value: taskmanagerapi
  - group: DockerHubSecrets  # This variable group should contain DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    docker build -t $(imageName):$(Build.BuildId) .
    docker tag $(imageName):$(Build.BuildId) $(Felison01)/$(imageName):latest
  displayName: 'Build and Tag Docker Image'

- script: |
    echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(Felison01)" --password-stdin
    docker push $(Felison01)/$(imageName):latest
  displayName: 'Push Docker Image to Docker Hub'
